"""Initial migration

Revision ID: 1f1a89a89dd9
Revises: 
Create Date: 2025-06-11 21:41:07.060673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1a89a89dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # First create tables
    op.create_table('stock_tip',
        sa.Column('id', sa.Integer(), nullable=False),
        # Add other columns here
        sa.PrimaryKeyConstraint('id')
    )
    
    # Then alter tables
    with op.batch_alter_table('stock_tip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_tip', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
